services:
  pinchflat:
    image: "ghcr.io/kieraneglin/pinchflat:latest"
    container_name: pinchflat
    ports:
      - "8945:8945"
    environment:
      TZ: "GB"
    volumes:
      - ${CONFIG_BASE}/pinchflat/config:/config
      - ${CONTENT_BASE}/youtube:/downloads
    restart: 'unless-stopped'
