services:
  pinchflat:
    image: "ghcr.io/kieraneglin/pinchflat:latest"
    ports:
      - "8945:8945"
    environment:
      TZ: "GB"
    volumes:
      - type: bind
        source: /media/joe/Big/YouTube/config
        target: /config
      - type: bind
        source: /media/joe/Big/YouTube/downloads
        target: /downloads
    restart: always
